project:
  type: website
  output-dir: docs
  
  
website:
  title: "Morgan L"
  navbar:
    left:
    - index.qmd
    - about.qmd
    - text: Data Viz
      menu:
      - whales and dolphins.qmd
      - seasons.qmd
      - project2.qmd
      - project3.qmd
      - project4.qmd
    - Resources.qmd
    
format:
  html:
    code-fold: true 
    theme:
      - yeti
    css: styles.css
    toc: true
    page-layout: full 

editor: visual



