project:
  type: website
  output-dir: docs
  
  
website:
  title: "Morgan L"
  navbar:
    left:
    - index.qmd
    - text: Data Viz
      menu:
      - whales and dolphins.qmd
      - seasons.qmd
      - project2.qmd
      - project3.qmd
      - project4.qmd
      - project5.qmd
    - text: "Resources"
      menu: 
      - project6.qmd
      - project7.qmd
    - my_slides.qmd
    
format:
  html:
    code-fold: true 
    theme:
      - sandstone
    css: styles.css
    toc: true
    page-layout: full 

editor: visual



